### ISSUE TITLE
filetransfer field is required - make it optional 

### ISSUE THREAD

**Issue by MaCXyLo** [Gix075/ajax-contact-form#4]
Heyyo,
thank you for your nice formular. :)

i tested it and have one question:
the filetransfer field is required, but not every user want to send a file while he sends a message.
it's a better idea to make it "optional" so the user can make a choice if he want to send a file or not.
Is there any setting available for this case?

Kind Regards,

**Comment by Gix075** [comment]
Hi @MaCXyLo on ajaxContactForm only name, email and message fields are strictly mandatory, and you can't remove them from the form (because the server script rejects the message if that fields are empty). All the rest of fields can be removed or you can set them as _not required_.
For make the attachments field as _not required_ you can simply remove the _**"validate"**_ class from the following hidden input. This rule is valid for all fields that you want to make not required.
```
<input type="hidden" class="validate" name="acf_attachments" id="acf_attachments">
```
I hope that can help you! Let me know if this solution works, otherwise i will fix it!

**Comment by MaCXyLo** [comment]
Hey,
i removed the validate class from acf_attachments [acf-demo.html](https://github.com/Gix075/ajax-contact-form/blob/master/dist/acf-demo.html) in line 84.
works like a charm.
thanks for that.

kind regards,
